config/routes.rb
Rails.application.routes.draw do

  get 'email/index'

	get "/pages/:page" => "pages#index", as: 'static'

  resources :home
  resources :email


  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/email_controller.rb
class EmailController < ApplicationController

require 'pony'

  def index
  	# Pony.mail(:to => 'kaco7777@gmail.com', :from => contact_params(:email), :subject => contact_params(:subject), :body => contact_params(:message))
  end

  private	

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :subject, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	render template: "pages/#{params[:page]}"
  end

  private

  def page_params
    params.require(:page).permit(:page);
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<%= image_tag asset_url('header_blue.jpg'), class: "img" %>  
<div class="overlay">
  <h1 class="name black-text">Christi Barker</h1>
  <h3 class="name_two black-text">Full Stack Web Developer</h3>
  <br>
  <div class="strheader">
    <div class="strspantext1 black-text">
      <div class="strIB">
        <div id="strength" class="strength black-text">
        </div>
      </div>
    </div>
  </div>
  <div class="under"></div>
</div>
  <!--     website projects-->
<div class="container-fluid">
  <div class="row">
    <h4 class="centered">My Projects</h4>
  </div>
  <div class="row projects">
    <div class="project col s12 m6 l4">
      <%= image_tag asset_url('blue_tile.jpg')%> 
      <div><a href="https://onyx-pole.herokuapp.com/" target="_blank" class="flow-text hover">Onyx Pole</a></div>
    </div>
    <div class="project col s12 m6 l4">
      <%= image_tag asset_url('blue_tile.jpg') %> 
      <div><a href="https://fedups.herokuapp.com/home" target="_blank" class="flow-text hover">FedUps</a></div>
    </div>
    <div class="project col s12 m6 l4">
      <%= image_tag asset_url('blue_tile.jpg') %> 
      <div><a href="https://nycdaohapp.herokuapp.com/users/sign_in" target="_blank" class="flow-text hover">Oh App</a></div>
    </div>
    <div class="project col s12 m6 l4">
      <%= image_tag asset_url('blue_tile.jpg') %> 
      <div><a href="http://christis-cookie-counter.herokuapp.com/" target="_blank" class="flow-text hover">Cookie Counter</a></div>
    </div>
    <div class="project col s12 m6 l4">
      <%= image_tag asset_url('blue_tile.jpg') %> 
      <div><a href="http://christis-wheel-of-fortune.herokuapp.com/" target="_blank" class="flow-text hover">Wheel of Fortune</a></div>
    </div>
    <div class="project col s12 m6 l4">
      <%= image_tag asset_url('blue_tile.jpg') %>
      <div><%= link_to "Details about projects", static_path('my_project'), class: "flow-text hover" %></div>
    </div>
  </div>
  <div class="skill white-text">
    <div class="col s4 m4"></div>
    <div class="col s4 m4">
      <h4 class="skill">Skills</h4>
    </div>
    <div class="col s4 m4"></div>
  </div>
  <div class="row skills white-text">
    <div class="col s2 m2"></div>
    <div class="col s3 m3">
      <ul>    
        <li class="center">Git</li>
        <li class="center">GitHub</li>
        <li class="center">Bootstrap</li>
        <li class="center">HTML/CSS</li>       
      </ul>
    </div>
    <div class="col s2 m2">
      <h2></h2>
      <ul>
        <li class="center">JQuery</li>
        <li class="center">Sinatra</li> 
        <li class="center">Ruby/Rails</li>
        <li class="center">Materialize</li>
      </ul>
    </div>
    <div class="col s3 m3">
      <ul>
        <li class="center">Heroku</li>
        <li class="center">Javascript</li>
        <li class="center">Coffeescript</li>
        <li class="center">SQL/Postgres</li>
      </ul>
    </div>
    <div class="col s2 m2"></div>
  </div>
  <div class="row">
    <div class="col s12 m12">
      <h4 class= "center">Recommendations</h4>
    </div>
  </div>
  <div class="row">
    <div class="col s1 m1"></div>
    <div class="col s4 m4 recomendations">
      <p>“I've seen first-hand her determination and ability to learn quickly. Like all good engineers, Christi's mind keeps working on the problem even when she's not busy coding at her keyboard.”</p>
      <div class= "snippets"><span>Owen Graupman
        - DevOps Architect at Willis Towers Watson's OneExchange</span></div>
      <p>"Christi is fearless! Inspires me with her quality of character, work ethic and determination. She shows a lot of care, passion, and a flair for design"</p>
      <div class="snippets"><span>Sam Lubin</span> - NYCDA</div>
    </div>
    <div class="col s2 m2"></div>
    <div class="col s4 m4 recomendations">
      <p>"Extremely driven and talented. Christi will continue to work through a problem until a sustainable and satisfactory result is achieved.”</p> 
      <div class="snippets"><span>Joshua Besser
        - Director Planning, Procurement & Energy - Nitrogen Products @ Dyno Nobel</span></div>
      <p>“Whatever she puts her mind to, she will see it through to the end. Get Christi on your team.”</p>
      <div class="snippets"><span>Ryan Richardson
       - Full Stack Web Developer</span></div>
      <p>“She's a doer and she's dedicated.”</p>
      <div class="snippets"><span>Casey Stinett
      - NYCDA</span></div>
    </div>
    <div class="col s1 m1"></div>
  </div>
</div>



    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
  	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Trade+Winds" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Bellefair|Kavivanar" rel="stylesheet">
   <link rel="stylesheet" type="text/css"
    media="screen and (max-device-width: 480px)"
    href="shetland.css" />
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
    <div class="nav-wrapper">
      <!-- <a href="#" class="brand-logo">Logo</a> -->
      <ul id="nav-mobile" class="right hide-on-med-and-down">
         <li><a href=""><%= link_to "Home", root_path %> </a></li>
        <li><a href=""><%= link_to "About Me", static_path('about_me') %> </a></li>
        <li><a href="" target="_blank"><%= link_to "Resume", asset_path("resume.pdf") %></a></li>
         <li><a href=""><%= link_to "My Projects", static_path('my_project') %> </a></li>
        <!-- li><a href="collapsible.html"><%# link_to "Contact", email_index_path %></a></li> -->
        <li><a href=""><%= link_to "Recommendations", static_path('recommendations') %> </a></li>
        <li><a class="white-text text-lighten-3" href="https://www.linkedin.com/in/christi-barker/" target="_blank"><%= image_tag('linkedin-logo.png', class: "smaller") %> </a></li>
        <li><a class="white-text text-lighten-3" href="https://github.com/christibarker" target="_blank"><%= image_tag('github.png', class: "smaller") %> </a></li>
      </ul>
    </div>
  </nav>
    <%= yield %>
    <footer class="page-footer">
      <div class="container">
        <div class="row sm_footer">
          <div class="col l6 s6">
            <h5 class="white-text font"><%= link_to "About Me", static_path('about_me') %></h5>
            <h5 class="white-text font"><%= link_to "Resume", asset_path("resume.pdf")%></h5>
            <h5 class="white-text font"><%= link_to "My Projects", static_path('my_project') %></h5>
            <h5 class="white-text font"><%= link_to "Recommendations", static_path('recommendations') %></h5>
          </div>
          <div class="col l4 offset-l2 s6">
            <h5 class="white-text font">Contact Me</h5>
            <ul>
              <li class="font_sm">text: (801) 616-7305</li>
              <li class="font_sm">email: christiobarker@gmail.com</li>
              <!-- <li class="right"><a class="grey-text text-lighten-3" href="https://www.linkedin.com/in/christi-ovchinnikov-barker/"><%# image_tag('linkedin-logo.png', class: "small left") %> </a></li>
              <li class="right"><a class="grey-text text-lighten-3" href="https://github.com/christibarker"><%# image_tag('github.png', class: "small") %> </a></li> -->
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
      <div class="container fluid">
        <span class="white-text"> © 2017 Copyright Text</span>
        <!-- <a class="grey-text text-lighten-4 right" href="#!">More Links</a> -->
        </div>
      </div>
    </footer>  
  </body>
</html>

app/views/pages/about_me.html.erb
<div class="row">
	<div class="col s12 m12">
		<h4 class= "center">About Me</h4>
		
	</div>
</div>
<!-- <div class="row">
	<div class="col s3 m3"></div>
	<div class="col s6 m6">
		
	</div>
	<div class="col s3 m3"></div>
</div> -->
<div class="row">
	<div class="col s2 m2">
		<%# image_tag asset_url('certificate_of_completion.jpg'), class: "certificate" %>
	</div>
	<div class="col s6 m6">
		<p class="about_me">Self-starting and creative web developer dedicated to building and optimizing the performance of user-centric, high-impact websites. Solid background in structuring, developing and implementing interactive websites. Leverage technical, analytical & problem-solving skills to create dynamic, high-speed websites, apps and platforms fueling competitive advantage and revenue growth. Extensive experience in relational database design and management, data modeling, applications development, testing, troubleshooting, and implementation. Proven ability to incorporate process improvement procedures and reengineering initiatives
to meet business goals and objects. </p>
		<p>Outstanding problem solving and analysis skills with exceptional facilitation, collaborative, and coordination abilities.</p>
		<p>Demonstrate the ability to synthesize information, prioritize business goals and drive results with a high sense of urgency.</p>
		<p>Solid communication, interpersonal and problem-solving skills; able to excel in challenging and deadline driven environments.</p>
		<p>Advanced web developer with experience in structuring, developing and implementing interactive websites.
		<p>Abilities in studying development tools, programming techniques & computing equipment maintaining personal networks.</p>
		<p>Experience designing, coding and modifying websites, from layout to function & according to a client's specifications.</p>
		<p>Proven ability to create dynamic websites.
		<p>Work closely with clients, marketing team, and back-end developer to develop a strategy and plan website releases.</p>
		<p>Updates job knowledge by participating in educational opportunities; reading professional publications; maintaining personal networks; participating in professional organizations.</p>
		<p class="interests"><strong>Personal Interests:</strong> Dance Fitness, Painting, Hiking, Reading, Self Improvement, Management Classes</p>
	</div>
	<div class="col s3 m3">
		<%= image_tag asset_url('christi.jpg'), class: "my_pic pic_border_2" %>
	</div>
	<div class="col s3 m3">
		<%= image_tag asset_url('headshot.jpg'), class: "my_pic pic_border" %>
	</div>
	<!-- <div class="row"> -->
		<!-- <div class="col s2 m2"></div> -->
		<!-- <div class="col s6 m6"> -->
			<%# image_tag asset_url('certificate_of_completion.jpg'), class: "certificate" %>
		<!-- <div class="col s2 m2"></div> -->
		<!-- </div> -->
	<!-- </div> -->
</div>

app/views/pages/my_project.html.erb
<div class="container-fluid">
  <div class="row">
        <h4 class="centered">My Projects</h4>
    <div class="col s12 m2 l2"></div>
  </div>
  <div class="row">
    <h5 class="centered_quote">Let me take you on a journey through my projects.</h5>
  </div>
  <div class="row details">
    <div class="col s1 s1 m1"></div>
    <div class="detail col s12 m4 l4">
      <div>
        <h5 class="centered_p"><a href="https://onyx-pole.herokuapp.com/" target="_blank">Onyx Pole</a></h5>
        <a href="https://onyx-pole.herokuapp.com/" target="_blank" ><%= image_tag asset_url('onyx.jpg'), class: "p_img flow-text" %></a>
        <p class="paragraph">For my final project I choose to redo one one of my favorite places to workout
        <a href="https://www.dancesaltlake.com/" target="_blank">Dance Salt Lake</a>. They outsource their scheduling system so I decided to create an in house scheduler to challenge myself. It is still a work in progress. I'm hoping to be able to present it to the company in the near future.</p>
      </div>
      <!-- <div class="border"></div> -->
    </div>
    <div class="col s2 m2"></div>
    <div class="detail col s12 m4 l4">
      <div>
        <h5 class="centered_p flow-text"><a href="https://nycdaohapp.herokuapp.com/users/sign_in" target="_blank">Oh App</a></h5>
        <a href="https://nycdaohapp.herokuapp.com/users/sign_in" target="_blank"><%= image_tag asset_url('oh_app_two.jpg'), class: "p_img flow-text" %></a>
        <p class="paragraph">This was our final group project. It is a project management site that has been game-a-fied. You can create departments, projects in that department and then assign employees to tasks.
        <span>In order to see all the great features of this site you must login.</span>
          <div>
            <p>email: sampleuser@mail.com</p>
            <p>password: password </p>
          </div>
        </p>
      </div>
      <!-- <div class="border"></div> -->
    </div>
    <div class="col s1 m1"></div>
  </div>
  <div class="row">
    <div class="col s1 m1"></div>
    <div class="detail col s12 m4 l4">
      <div>
        <h5 class="centered_p flow-text"><a href="https://fedups.herokuapp.com/home" target="_blank">Fedups</a></h5>
        <a href="https://fedups.herokuapp.com/home" target="_blank"><%= image_tag asset_url('shipped.jpg'), class: "p_img flow-text" %></a>
        <p class="paragraph">This project uses join tables. I wanted the jobs and boats to show up on corresponding pages. In order to see all the features of this site you must login.
          <div>
            <p>username: sampleuser</p>
            <p>email: sampleuser@mail.com</p>
            <p>password: password</p>
          </div>
        </p>
      </div>
      <!-- <div class="border"></div> -->
    </div>
    <div class="col s2 m2"></div>
    <div class="detail col s12 m4 l4">
      <div>
        <h5 class="centered_p"><a href="http://christis-wheel-of-fortune.herokuapp.com/" target="_blank">Wheel of Fortune</a></h5>
        <a href="http://christis-wheel-of-fortune.herokuapp.com/" target="_blank"><%= image_tag asset_url('wof_two.jpg'), class: "p_img" %></a>
        <p class="paragraph">When I created this project I had only been coding for about 4 weeks. I was bound and determined to make the letters pop up the same way they do it on the wheel of fortune game, which turned into a challenge. I have it currently set up so one can pick which color you would like to play. Enjoy!</p>
      </div>
      <!-- <div class="border"></div> -->
    </div>
    <div class="col s1 m1"></div>
  </div>
  <div class="row">
    <div class="col s1 m1"></div>
    <div class="detail col s12 m3 l3">
      <div>
        <h5 class="centered_p flow-text"><a href="http://christis-wheel-of-fortune.herokuapp.com/" target="_blank">Cookie Counter</a></h5>
        <a href="http://christis-wheel-of-fortune.herokuapp.com/" target="_blank"><%= image_tag asset_url('cookie_two.jpg'), class: "p_img" %></a>
        <p class="paragraph">With a bootcamp it really pushes you hard. Sometimes you have to turn assignments in the next day. This was prior to materialize and bootstrap. This was the first project I felt that I could stretch myself beyond the basic requirements.</p>
      </div>
      <!-- <div class="border"></div> -->
    </div>
    <div class="col s2 m2"></div>
    <div class="detail col s12 m3 l3"><%= image_tag asset_url('certificate_of_completion.jpg'), class: "certificate" %></div>
    <div class="col s1 m1"></div>
</div>

app/views/pages/my_projects.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="detail col s12 m2 l2"></div>
      <div class="detail col s12 m8 l8">
        <h4 class="centered">My Projects</h4>
      </div>
    <div class="detail col s12 m2 l2"></div>
  </div>
  <div class="row">
    <div class="detail col s12 m2 l2"></div>
    <div class="detail col s12 m8 l8">
      <h5 class="centered">Let me take you on a journey through my projects.</h5>
    </div>
    <div class="detail col s12 m2 l2"></div>
  </div>
	<div class="row details">
    <div class="detail col s12 m8 l8">
      <%= image_tag asset_url('projects.jpg') %> 
      <div class="flow-text>">
      	<%= image_tag asset_url('onyx.jpg'), class: "p_img flow-text" %>
      		<h5 class="centered_p flow-text"><a href="https://www.dancesaltlake.com/" target="_blank">Onyx Pole</a></h5>
      		<p class="paragraph flow-text">For my final project I choose to redo one one of my favorite places to workout
      		<a href="https://www.dancesaltlake.com/" target="_blank">Dance Salt Lake</a>. They outsource their scheduling system so I decided to create an in house scheduler to challenge myself. It is still a work in progress. I'm hoping to be able to present it to the company in the near future.</p>
      	<%= image_tag asset_url('dance_sl.jpg'), class: "p_img_two flow-text" %>
    	</div>
    </div>
		<div class="detail col s12 m8 l8">
      <%= image_tag asset_url('projects.jpg') %> 
      <div class="flow-text>">
      	<%= image_tag asset_url('shipped.jpg'), class: "p_img flow-text" %>
      		<h5 class="centered_p flow-text"><a href="https://fedups.herokuapp.com/home" target="_blank">Fedups</a></h5>
      		<p class="paragraph flow-text">In order to see all the great features of this site you must login.
      		<span>username: sampleuser</span>
      		<span>email: sampleuser@mail.com</span>
      	  <span>password: password</span>
      	 </p>
      	<%= image_tag asset_url('shipped_two.jpg'), class: "p_img_two flow-text" %>
    	</div>
    </div>
		<div class="detail col s12 m8 l8">
      <%= image_tag asset_url('projects.jpg') %> 
      <div class="flow-text>">
      	<%= image_tag asset_url('ohapp.jpg'), class: "p_img flow-text" %>
      		<h5 class="centered_p flow-text"><a href="https://nycdaohapp.herokuapp.com/users/sign_in" target="_blank">Oh App</a></h5>
      		<p class="paragraph flow-text">This was our final group project. It is a project management site that has been game-a-fied. You can create departments, projects in that department and then assign employees to tasks. 
      		<span>In order to see all the great features of this site you must login.</span>
      		<span>email: sampleuser@mail.com</span>
      	  <span>password: </span>
      	 </p>
      	<%= image_tag asset_url('oh_app_two.jpg'), class: "p_img_two flow-text" %>
    	</div>
    </div>
    <div class="detail col s12 m8 l8">
      <%= image_tag asset_url('projects.jpg') %> 
      <div class="flow-text>">
      	<%= image_tag asset_url('wof_one.jpg'), class: "p_img flow-text" %>
      		<h5 class="centered_p flow-text"><a href="http://christis-wheel-of-fortune.herokuapp.com/" target="_blank">Wheel of Fortune</a></h5>
      		<p class="paragraph flow-text">When I created this project I had only been coding for about 4 weeks. I was bound and determined to make the letters pop up the same way they do it on the wheel of fortune game, which turned into a challenge. I have it currently set up so one can pick which color you would like to play. Enjoy!</p>
      	<%= image_tag asset_url('wof_two.jpg'), class: "p_img_two flow-text" %>
    	</div>
    </div>
    <div class="detail col s12 m8 l8">
      <%= image_tag asset_url('projects.jpg') %> 
      <div class="flow-text>">
      	<%= image_tag asset_url('cookie_two.jpg'), class: "p_img flow-text" %>
      		<h5 class="centered_p flow-text"><a href="http://christis-wheel-of-fortune.herokuapp.com/" target="_blank">Cookie Counter</a></h5>
      		<p class="paragraph flow-text">With a bootcamp it really pushes you hard. Sometimes you have to turn assignments in the next day. This was prior to materialize and bootstrap. This was the first project I felt that I could stretch myself beyond the basic requirements.</p>
      	<%= image_tag asset_url('cookie_one.jpg'), class: "p_img_two flow-text" %>
    	</div>
    </div>
	
</div>

app/views/pages/recommendations.html.erb
<div class="row">
	<div class="col s12 m12">
		<h4 class= "center">Recommendations</h4>
	</div>
</div>
<div class="row">
	<div class="col s1 m1"></div>
	<div class="col s4 m4 recomendation">
		<!-- <p>December 2, 2017, Owen was Christi’s mentor</p> -->
		<p class="font_size">"As a mentor for Christi, I've seen first-hand her determination and ability to learn quickly. Like all good engineers, Christi's mind keeps working on the problem even when she's not busy coding at her keyboard. Often, she keeps plugging away at her assignments on her own time, even after completing them, to master concepts she's learned. In particular, her passion for learning during the Ruby and Sinatra projects really stood out. I would recommend Christi for any web development position that requires a hard-working, creative individual."</p>
		<div class="border"><span>Owen Graupman - DevOps Architect at Willis Towers Watson's OneExchange</span></div>

		<!-- <p>January 2, 2018, Joshua was Christi’s mentor</p> -->
		<p class="font_size">"Christi is extremely driven and talented. She has shown great dedication in her programming journey and is extremely creative in problem solving and solution generation. Christi will continue to work through a problem until a sustainable and satisfactory result is achieved. I am confident that Christi will thrive with a new team and will certainly help further the company mission and success."</p>
		<div class="border"><span>Joshua Besser - Director Planning, Procurement & Energy - Nitrogen Products @ Dyno Nobel</span></div>
	</div>
	<div class="col s2 m2"></div>
	<div class="col s4 m4">
		<!-- <p>January 5, 2018, Christi was a client of Samuel’s<p> -->
		<p class="font_size">"Christi is fearless! Christi's perseverance in the face of adversity is second to none. She routinely inspires me with her quality of character, work ethic and determination. In class, she visibly demonstrated exponential growth as a learner and developer. In her work, she shows a lot of care, passion, and a flair for design. Never lacking for motivation and never skimping on effort, Christi is an asset to any team who needs a job done."</p>
		<div class="border"><span>Samuel Lubin - Success Coach at New York Code + Design Academy</span></div>

		<!-- <p>January 2, 2018, Ryan and Christi were students together</p> -->
		<p class="font_size">"I am lucky to have studied with Christi. She is very tenacious and has a lot of heart. I am convinced that whatever she puts her mind to, she will see it through to the end. You should get Christi on your team."</p>
		<div class="border"><span> Ryan Richardson - Full Stack Web Developer</span></div>

	<!-- 	<p>December 30, 2017, Casey was Christi’s teacher</p> -->
		<p class="font_size">"Christi has some incredible grit. She keeps going and gets done what needs to get done. She took on a pretty big project of redoing a website that was outdated. Her redesign not only brought the site into 2017, but was simple, clean, and user friendly. She's a doer and she's dedicated."</p>
		<div class="border"><span>Casey Stinnett - Lead Instructor at NYCDA (SLC)</span></div>		
	</div>
	<div class="col s1 m1"></div>
</div>